services:
  app:
    build: .
    ports:
      - '${APP_PORT}:5000'
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}

  minio:
    image: quay.io/minio/minio
    container_name: hrcrm_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
